### ISSUE TITLE
Linear actuator not working after merge

### ISSUE THREAD

**Issue by byu014** [Miguel9r/CS179J-Team10#6]

**Comment by KLabog001** [comment]
Arduino code with integrated linear actuator and camera functionality does not work with hardware and processing program. I retested the old code to make sure it wasn't my wiring that was defective and the wiring still works. The two codes have different pins for the linear actuator but I do remember to change that when attempting to run the new code.

**Comment by KLabog001** [comment]
Debugged - Linear Actuator and Camera code conflict on baud rate due to module capabilities. Compromised at 28800 baud rate from camera 250000 and linear actuator's 9600. Issues with wiring components may arise.
